<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Automatou.TerminalShell</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../Source/Automatou.Kernel/Automatou.Kernel.csproj" />
    </ItemGroup>
</Project>
