<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SimplePaint3DShell</RootNamespace>
    <AssemblyName>SimplePaint3DShell</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' != 'Debug'">
    <Compile Remove="Tests/**/*.cs" />
  </ItemGroup>
</Project>
